// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: webauthn.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :one
INSERT INTO webauthn_credentials (
    user_id, credential_id, public_key, aaguid, clone_warning,
    attachment, transport, backup_eligible, backup_state, sign_count
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, credential_id, public_key, aaguid, clone_warning, attachment, transport, backup_eligible, backup_state, sign_count, created_at, last_used_at
`

type CreateWebAuthnCredentialParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	CredentialID   []byte      `json:"credential_id"`
	PublicKey      []byte      `json:"public_key"`
	Aaguid         pgtype.UUID `json:"aaguid"`
	CloneWarning   pgtype.Bool `json:"clone_warning"`
	Attachment     pgtype.Text `json:"attachment"`
	Transport      []string    `json:"transport"`
	BackupEligible pgtype.Bool `json:"backup_eligible"`
	BackupState    pgtype.Bool `json:"backup_state"`
	SignCount      pgtype.Int8 `json:"sign_count"`
}

func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, createWebAuthnCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.Aaguid,
		arg.CloneWarning,
		arg.Attachment,
		arg.Transport,
		arg.BackupEligible,
		arg.BackupState,
		arg.SignCount,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.Aaguid,
		&i.CloneWarning,
		&i.Attachment,
		&i.Transport,
		&i.BackupEligible,
		&i.BackupState,
		&i.SignCount,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :exec
DELETE FROM webauthn_credentials
WHERE credential_id = $1 AND user_id = $2
`

type DeleteWebAuthnCredentialParams struct {
	CredentialID []byte      `json:"credential_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnCredential, arg.CredentialID, arg.UserID)
	return err
}

const getWebAuthnCredentialByID = `-- name: GetWebAuthnCredentialByID :one
SELECT id, user_id, credential_id, public_key, aaguid, clone_warning, attachment, transport, backup_eligible, backup_state, sign_count, created_at, last_used_at FROM webauthn_credentials
WHERE credential_id = $1
`

func (q *Queries) GetWebAuthnCredentialByID(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByID, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.Aaguid,
		&i.CloneWarning,
		&i.Attachment,
		&i.Transport,
		&i.BackupEligible,
		&i.BackupState,
		&i.SignCount,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getWebAuthnCredentialsByUserID = `-- name: GetWebAuthnCredentialsByUserID :many
SELECT id, user_id, credential_id, public_key, aaguid, clone_warning, attachment, transport, backup_eligible, backup_state, sign_count, created_at, last_used_at FROM webauthn_credentials
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWebAuthnCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, getWebAuthnCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.Aaguid,
			&i.CloneWarning,
			&i.Attachment,
			&i.Transport,
			&i.BackupEligible,
			&i.BackupState,
			&i.SignCount,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebAuthnCredentialCloneWarning = `-- name: UpdateWebAuthnCredentialCloneWarning :exec
UPDATE webauthn_credentials
SET clone_warning = $2
WHERE credential_id = $1
`

type UpdateWebAuthnCredentialCloneWarningParams struct {
	CredentialID []byte      `json:"credential_id"`
	CloneWarning pgtype.Bool `json:"clone_warning"`
}

func (q *Queries) UpdateWebAuthnCredentialCloneWarning(ctx context.Context, arg UpdateWebAuthnCredentialCloneWarningParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredentialCloneWarning, arg.CredentialID, arg.CloneWarning)
	return err
}

const updateWebAuthnCredentialSignCount = `-- name: UpdateWebAuthnCredentialSignCount :exec
UPDATE webauthn_credentials
SET sign_count = $2, last_used_at = NOW()
WHERE credential_id = $1
`

type UpdateWebAuthnCredentialSignCountParams struct {
	CredentialID []byte      `json:"credential_id"`
	SignCount    pgtype.Int8 `json:"sign_count"`
}

func (q *Queries) UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredentialSignCount, arg.CredentialID, arg.SignCount)
	return err
}
