basePath: /
definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.GenerateOTPCodesResponse:
    properties:
      CurrentCode:
        type: string
      CurrentExpireAt:
        type: string
      Id:
        type: integer
      NextCode:
        type: string
      NextExpireAt:
        type: string
    type: object
  dto.MessageResponse:
    properties:
      message:
        type: string
    type: object
  models.LoginEvent:
    properties:
      id:
        type: integer
      ip_address:
        type: string
      timestamp:
        type: string
      user_agent:
        type: string
      user_id:
        type: integer
    type: object
  models.OTP:
    properties:
      active:
        type: boolean
      algorithm:
        type: string
      counter:
        type: integer
      created_at:
        type: string
      digits:
        type: integer
      id:
        type: integer
      issuer:
        type: string
      label:
        type: string
      method:
        type: string
      period:
        type: integer
      secret:
        type: string
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      provider:
        type: string
      provider_id:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: anhngw@gmail.com
    name: Alan Nguyen
    url: http://www.2fair.vip/support
  description: This is the API documentation for the 2FAir application.
  license:
    name: GNU General Public License v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  termsOfService: http://swagger.io/terms/
  title: 2FAir API
  version: "1.0"
paths:
  /auth/google:
    get:
      consumes:
      - application/json
      description: Authenticate a user using Google OAuth
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login with Google
      tags:
      - auth
  /auth/google/callback:
    get:
      consumes:
      - application/json
      description: Handle the callback from Google OAuth
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Google OAuth callback
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Log out the current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Logout
      tags:
      - auth
  /auth/me:
    get:
      consumes:
      - application/json
      description: Get the currently authenticated user's information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get current user
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh the access token using the refresh token cookie
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Refresh access token
      tags:
      - auth
  /login-history:
    get:
      consumes:
      - application/json
      description: Get the login history for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.LoginEvent'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Get login history
      tags:
      - auth
  /otp:
    get:
      consumes:
      - application/json
      description: Get all OTPs for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.OTP'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: List OTPs
      tags:
      - otp
    post:
      consumes:
      - application/json
      description: Add a new OTP for the authenticated user
      parameters:
      - description: OTP details
        in: body
        name: otp
        required: true
        schema:
          $ref: '#/definitions/models.OTP'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Add OTP
      tags:
      - otp
  /otp/{id}:
    put:
      consumes:
      - application/json
      description: Edit an existing OTP
      parameters:
      - description: OTP ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated OTP details
        in: body
        name: otp
        required: true
        schema:
          $ref: '#/definitions/models.OTP'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Edit OTP
      tags:
      - otp
  /otp/{id}/inactivate:
    post:
      consumes:
      - application/json
      description: Mark an OTP as inactive
      parameters:
      - description: OTP ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Inactivate OTP
      tags:
      - otp
  /otps/codes:
    get:
      consumes:
      - application/json
      description: Generate current and next OTP codes for the user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.GenerateOTPCodesResponse'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Generate OTP codes
      tags:
      - otps
swagger: "2.0"
