// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: encryption_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserEncryptionKey = `-- name: CreateUserEncryptionKey :one
INSERT INTO user_encryption_keys (user_id, webauthn_credential_id, encrypted_dek, key_version)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, webauthn_credential_id, encrypted_dek, key_version, created_at
`

type CreateUserEncryptionKeyParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	WebauthnCredentialID pgtype.UUID `json:"webauthn_credential_id"`
	EncryptedDek         []byte      `json:"encrypted_dek"`
	KeyVersion           int32       `json:"key_version"`
}

func (q *Queries) CreateUserEncryptionKey(ctx context.Context, arg CreateUserEncryptionKeyParams) (UserEncryptionKey, error) {
	row := q.db.QueryRow(ctx, createUserEncryptionKey,
		arg.UserID,
		arg.WebauthnCredentialID,
		arg.EncryptedDek,
		arg.KeyVersion,
	)
	var i UserEncryptionKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WebauthnCredentialID,
		&i.EncryptedDek,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveUserEncryptionKey = `-- name: GetActiveUserEncryptionKey :one
SELECT id, user_id, webauthn_credential_id, encrypted_dek, key_version, created_at FROM user_encryption_keys
WHERE user_id = $1
ORDER BY key_version DESC
LIMIT 1
`

func (q *Queries) GetActiveUserEncryptionKey(ctx context.Context, userID pgtype.UUID) (UserEncryptionKey, error) {
	row := q.db.QueryRow(ctx, getActiveUserEncryptionKey, userID)
	var i UserEncryptionKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WebauthnCredentialID,
		&i.EncryptedDek,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getUserEncryptionKeyByCredential = `-- name: GetUserEncryptionKeyByCredential :one
SELECT id, user_id, webauthn_credential_id, encrypted_dek, key_version, created_at FROM user_encryption_keys
WHERE user_id = $1 AND webauthn_credential_id = $2
ORDER BY key_version DESC
LIMIT 1
`

type GetUserEncryptionKeyByCredentialParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	WebauthnCredentialID pgtype.UUID `json:"webauthn_credential_id"`
}

func (q *Queries) GetUserEncryptionKeyByCredential(ctx context.Context, arg GetUserEncryptionKeyByCredentialParams) (UserEncryptionKey, error) {
	row := q.db.QueryRow(ctx, getUserEncryptionKeyByCredential, arg.UserID, arg.WebauthnCredentialID)
	var i UserEncryptionKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WebauthnCredentialID,
		&i.EncryptedDek,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getUserEncryptionKeyByVersion = `-- name: GetUserEncryptionKeyByVersion :one
SELECT id, user_id, webauthn_credential_id, encrypted_dek, key_version, created_at FROM user_encryption_keys
WHERE user_id = $1 AND key_version = $2
`

type GetUserEncryptionKeyByVersionParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	KeyVersion int32       `json:"key_version"`
}

func (q *Queries) GetUserEncryptionKeyByVersion(ctx context.Context, arg GetUserEncryptionKeyByVersionParams) (UserEncryptionKey, error) {
	row := q.db.QueryRow(ctx, getUserEncryptionKeyByVersion, arg.UserID, arg.KeyVersion)
	var i UserEncryptionKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WebauthnCredentialID,
		&i.EncryptedDek,
		&i.KeyVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getUserEncryptionKeys = `-- name: GetUserEncryptionKeys :many
SELECT id, user_id, webauthn_credential_id, encrypted_dek, key_version, created_at FROM user_encryption_keys
WHERE user_id = $1
ORDER BY key_version DESC
`

func (q *Queries) GetUserEncryptionKeys(ctx context.Context, userID pgtype.UUID) ([]UserEncryptionKey, error) {
	rows, err := q.db.Query(ctx, getUserEncryptionKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserEncryptionKey{}
	for rows.Next() {
		var i UserEncryptionKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WebauthnCredentialID,
			&i.EncryptedDek,
			&i.KeyVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
